# Generated by Django 5.2.4 on 2025-07-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbanuser',
            name='fullname',
            field=models.CharField(max_length=150),
        ),
    ]
